---
- apt: pkg=apt-transport-https state=installed
- apt_repository: repo='deb https://artifacts.elastic.co/packages/5.x/apt stable main' state=present
- apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present
